export const USER_GET_APPROVED_COURSES_REQUEST = "USER_GET_APPROVED_COURSES_REQUEST";
export const USER_GET_APPROVED_COURSES_SUCCESS = "USER_GET_APPROVED_COURSES_SUCCESS";
export const USER_GET_APPROVED_COURSES_FAIL = "USER_GET_APPROVED_COURSES_FAIL";