//DANH SACH KHOA HOC
export const GET_COURSE_LIST_REQUEST = 'GET_COURSE_LIST_REQUEST';
export const GET_COURSE_LIST_SUCCESS = 'GET_COURSE_LIST_SUCCESS';
export const GET_COURSE_LIST_FAIL = 'GET_COURSE_LIST_FAIL';

// DANH SACH KHOA HOC THEO DANH MUC
export const GET_COURSE_ITEM_REQUEST = 'GET_COURSE_ITEM_REQUEST';
export const GET_COURSE_ITEM_SUCCESS = 'GET_COURSE_ITEM_SUCCESS';
export const GET_COURSE_ITEM_FAIL = 'GET_COURSE_ITEM_FAIL';

// CATEGORIES DANH MUC KHOA HOC
export const GET_CATEGORIES_REQUEST ='GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS ='GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAIL ='GET_CATEGORIES_FAIL'

// CHI TIET KHOA HOC
export const GET_COURSE_DETAIL_REQUEST = 'GET_COURSE_DETAIL_REQUEST';
export const GET_COURSE_DETAIL_SUCCESS = 'GET_COURSE_DETAIL_SUCCESS';
export const GET_COURSE_DETAIL_FAIL = 'GET_COURSE_DETAIL_FAIL';