export const GET_COURSES_AWAIT_APPROVE_REQUEST = "GET_COURSES_AWAIT_APPROVE_REQUEST";
export const GET_COURSES_AWAIT_APPROVE_SUCCESS = "GET_COURSES_AWAIT_APPROVE_SUCCESS";
export const GET_COURSES_AWAIT_APPROVE_FAIL = "GET_COURSES_AWAIT_APPROVE_FAIL";