export const UPLOAD_IMG_COURSE_REQUEST = 'UPLOAD_IMG_COURSE_REQUEST';
export const UPLOAD_IMG_COURSE_SUCCESS = 'UPLOAD_IMG_COURSE_SUCCESS';
export const UPLOAD_IMG_COURSE_FAIL = 'UPLOAD_IMG_COURSE_FAIL';

export const UPDATE_IMG_COURSE_REQUEST = 'UPDATE_IMG_COURSE_REQUEST';
export const UPDATE_IMG_COURSE_SUCCESS = 'UPDATE_IMG_COURSE_SUCCESS';
export const UPDATE_IMG_COURSE_FAIL = 'UPDATE_IMG_COURSE_FAIL';